#! /bin/sh

# TODO: test
#   branch       with remote branch
#   dcommit
#   push

# test done for:
#   abort
#   add
#   branch       -d, -D, create new branch
#   checkout     basic, -b with switch, from reset
#   commit
#   diff
#   import
#   init (with and without arguments)
#   log
#   rebase
#   reset
#   rm
#   show
#   status

# sprinkle 'set -e' whenever useful
# audit quiet/verbose/debug
# commit --amend
# commit -m/-F
# import -m/-F
# avoid forking on dirname/basename

# Shell sanitization
# ------------------

if test -n "${ZSH_VERSION+set}" && (emulate sh) >/dev/null 2>&1; then
  emulate sh
  NULLCMD=:
  alias -g '${1+"$@"}'='"$@"'
elif test -n "${BASH_VERSION+set}" && (set -o posix) >/dev/null 2>&1; then
  set -o posix
else
  # Try executing under a good shell
  if test -n "$RECURSIVE_SHELL"; then
    echo you have a problem ; exit 1
  fi
  export RECURSIVE_SHELL=1
  bash -c : > /dev/null 2>&1 && exec bash -c '$0 "$@"' $0 "$@"
  zsh -c : > /dev/null 2>&1 && exec zsh -c '$0 "$@"' $0 "$@"
fi

# Help message (placed as soon as possible)
# ------------

usage () {
  echo 'gilt - simple git-inspired local branch management for svn'
  echo
  echo "Usage: $progname COMMAND OPTIONS..."
  echo
  echo 'Repository management:'
  echo '  init                         create .gilt directory'
  echo '  reset [--force] [--soft]     get out of the current local branch'
  echo '                               --force does so even if there are changes'
  echo '                               --soft does not revert the branch changes'
  echo
  echo 'Local branch operation:'
  echo '  add [-a | FILE...]           track content of the files in the patch'
  echo '  branch BRANCH [SVN-BRANCH]   create local branch on top of svn branch'
  echo '  branch -d|-D BRANCH          eliminate local branch'
  echo '  checkout BRANCH              start working on the given local branch'
  echo '  checkout -b BRANCH [SVN-BRANCH] start working on a new local branch'
  echo '  commit [-a | FILE...]        commit changes on top of current branch'
  echo '  import [-pN] FILE            add a patch on top of current branch'
  echo '  rm [FILE...]                 do not track content of the files'
  echo
  echo 'Showing information:'
  echo '  diff [FILE...]               print diffs with tip of current branch'
  echo '  log [-r|--reverse] [BRANCH]  concatenate all the logs in the branch'
  echo '  show [BRANCH] [NUMBER]       show one patch in a branch (default last)'
  echo '  show -a [BRANCH]             show all patches in a branch'
  echo '  status [FILE...]             print changed files with tip of current branch'
  echo
  echo 'Synchronization:'
  echo '  abort                        abort in progress operations'
  echo '  rebase [SVN-BRANCH]          svn update or switch + refresh patches'
  echo '  push                         starts svn commit with "gilt log" as output'
  echo '  dcommit                      commits each patch separately'
  echo
  exit "$@"
}

# Technical documentation
# -----------------------
#
# Structure of the repository:
#  .gilt
#    HEAD
#    name (for each local branch)
#      INFO
#      tree/
#        modified files
#      patches/
#        p1
#        p2
#        p3
#        ...
#
# Data in the INFO file:
# BRANCH=<svn branch url>
# BASEREV=<svn base rev>
# NUMPATCHES=<number of patches>
#
# TODO: new-files, removed-files

# Functions for generic use
# -------------------------

error_msg () {
  echo "$progname:" "$@" >&2
}

error () {
  error_msg "$@"
  exit 1
}

usage_error () {
  error_msg "$@"
  usage 1
}

is_parent_of_pwd () {
  case "$PWD" in
    "$1"*) return 0 ;;
    *) return 1 ;;
  esac
}

# mkdir -p emulation based on the mkinstalldirs script.
mkdir_p () {
  local file pathcomp oIFS IFS d
  for file
  do
    case $file in
      /*) pathcomp=/ ;;
      *)  pathcomp= ;;
    esac
    oIFS=$IFS
    IFS=/
    set fnord $file
    shift
    IFS=$oIFS

    errstatus=0
    for d
    do
      test "x$d" = x && continue
      pathcomp=$pathcomp$d
      case $pathcomp in
        -*) pathcomp=./$pathcomp ;;
      esac

      if test ! -d "$pathcomp"; then
        debug creating "$pathcomp"
        mkdir "$pathcomp" || lasterr=$?
        test -d "$pathcomp" || errstatus=$lasterr
      fi
      pathcomp=$pathcomp/
    done
  done
  return "$errstatus"
}

squeeze_blanks ()
{
  sed -n '
     # delete all (leading) blanks
     /./!d

     # get here: so there is a non empty
     :x
     # print it
     p
     # get next
     n
     # got chars? print it again, etc...
     /./bx

     # no, got an empty line
     :z
     # get next, if last line we finish here so no trailing
     # empty lines are written
     n
     # also empty? then ignore it, and get next... this will
     # remove ALL empty lines
     /./!bz

     # all empty lines were deleted/ignored, but we have a non empty.  As
     # what we want to do is to squeeze, insert a blank line artificially
     i\

     bx'
}


# gilt-specific helper functions.
# -------------------------------

# svn_info FIELD
# extract the field from the repository and echo it
svn_info () {
  svn info | sed -n "s/^$1: //p"
}

# svn_revert
# same as "svn revert -R", but cheaper because it uses /tree files
svn_revert () {
  # TODO: avoid xargs -r
  (cd "$SVNTOP"
  test "$qv" = -v || exec > /dev/null
  gilt_modified_files | xargs -r -d'\n' svn revert)
}

# get_svn_info
# set SVNTOP, SVNROOT, SVNBRANCH, SVNSUBDIR
get_svn_info () {
  local newroot oldwd
  test -d .svn || error not in a Subversion repository.
  set -e
  SVNROOT=`svn_info 'Repository Root'`
  oldwd=$PWD
  while :; do
    SVNTOP=$PWD
    cd ..
    test -d .svn || break
    newroot=`svn_info 'Repository Root'`
    test "$newroot" != "$SVNROOT" && break
  done
  cd "$SVNTOP"
  SVNBRANCH=`svn_info URL`
  SVNBRANCH=${SVNBRANCH#$SVNROOT/}
  cd "$oldwd"
  SVNSUBDIR=${oldwd#$SVNTOP}
  set +e
  GILTROOT=${GILTROOT-$SVNTOP/.svn/.gilt}
}

# test_gilt_branch BRANCH
test_gilt_branch () {
  case "$1" in
    '' | -* | */* | . | ..)
      error bad branch name
      ;;
    *)
      if test -d "$GILTROOT"; then
        test -f "$GILTROOT/$1/INFO" || error nonexistent branch "$1"
      else
        error not in a gilt tree.
      fi
      ;;
  esac
  return 0
}

# get_gilt_info [--init|--need-branch|BRANCH]
# set GILTHEAD and possibly set BRANCH, BASEREV, NUMPATCHES
get_gilt_info () {
  case "$1" in
    */* | . | ..)
      error bad branch name
      ;;
    '' | --*)
      if test -f "$GILTROOT"/HEAD; then
        GILTHEAD=`cat "$GILTROOT"/HEAD`
      fi
      if test -z "$GILTHEAD"; then
        if test -d "$GILTROOT"; then
          if test "$1" = --need-branch; then
	    error not on a gilt branch
          fi
        elif test "$1" = --init; then
          mkdir "$GILTROOT"
        else
          error not in a gilt tree.
        fi
      fi
      ;;
    *)
      if test -d "$GILTROOT"; then
        GILTHEAD="$1"
      else
        error not in a gilt tree.
      fi
      ;;
  esac
  if test -n "$GILTHEAD"; then
    test -f "$GILTROOT/$GILTHEAD/INFO" || error nonexistent branch "$GILTHEAD"
    set -e
    . "$GILTROOT/$GILTHEAD/INFO"
    set +e
  fi
}

make_svn_absolute_path ()
{
  local oldwd
  case $2 in
    $SVNTOP/*) eval $1='${2#$SVNTOP}' ;;
    /*) return 1;;
    .*[!/] | [!.]*)			# not . or ./ or .// etc.
      oldwd=$PWD
      if test -d "$2"; then
        dir=$2
        file=
      else
        dir=`dirname "$2"`
        file=/`basename "$2"`
      fi
      cd "$dir"
      is_parent_of_pwd $SVNTOP || return 1
      eval $1='${PWD#$SVNTOP}$file'
      cd "$oldwd"
      ;;
    *)					# . or ./ or .// etc.
      eval $1='$SVNSUBDIR'
      ;;
  esac
  eval $1='${'$1'#/}'
}

files_in_patch () {
  sed -ne 's/^Index: //p' "$@"
  #sed -e '/^+++ /!d;s///;s/	.*//p' "$@"
}

# Conditional execution of commands

cond_set ()
{
  eval "$1"'()
  {
    "$@"
  }'
}

cond_reset ()
{
  eval "$1"'()
  {
    :
  }'
}

# exit if the tree has changes compared to the top of the gilt branch
# or, if there is no active gilt branch, to the top of the svn branch
check_no_changes ()
{
  local line
  if test -z "$GILTHEAD"; then
    return 0
  else
    gilt_has_changes || error modified tree, "$@"
  fi
}

gilt_has_changes ()
{
  gilt_modified_files "$@" | (while read file; do
    cmp "$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file" > /dev/null 2>&1 || exit 1
  done)
}

do_status ()
{
  gilt_modified_files "$@" | while read file; do
    if cmp "$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file" > /dev/null; then
      :
    else
      echo "M	$file"
    fi
  done
}

check_no_overlapping_changes ()
{
  # TODO: avoid xargs -r
  local oldwd
  oldwd=$PWD
  cd "$SVNTOP"
  if gilt_modified_files "$@" | xargs -r -d'\n' svn status -q 2>/dev/null | \
      { read line; test "$line" = M; }; then
    return 1
  else
    return 0
  fi
}

# save [BRANCH]
# save branch info to BRANCH/INFO (/INFO if FILE is omitted)
save ()
{
  cat > "$GILTROOT/${1-$GILTHEAD}/INFO" <<EOF
BRANCH='`echo $BRANCH | sed "s/'/'\\\\''/g"`'
BASEREV='`echo $BASEREV | sed "s/'/'\\\\''/g"`'
NUMPATCHES='`echo $NUMPATCHES | sed "s/'/'\\\\''/g"`'
FIRSTPATCH='`echo $FIRSTPATCH | sed "s/'/'\\\\''/g"`'
EOF
}

# reconstruct DIR FILES...
# Copy the current svn revision of each FILE to $GILTROOT/$GILTHEAD/DIR/FILE
reconstruct ()
{
  local i dest
  dest=$1
  shift
  for i
  do
    dir=`dirname "$i"`
    mkdir_p "$GILTROOT/$GILTHEAD/$dest/$dir"
    cp ${qvv} "$i" $GILTROOT/$GILTHEAD/$dest/$i
    svn diff "$i" | $PATCH -R "$GILTROOT/$GILTHEAD/$dest/$i" > /dev/null
  done
}

# extract_commit_msg FILES...
# Extract the commit message from the FILES
extract_commit_msg ()
{
  local i
  if test $# = 0; then
    sed -n '/^Index:/q;/^---/q;/^diff /q;p' "$@"
  else
    # Emulate sed -s '/^Index:/,$d; /^---/,$d; /^diff /,$d'
    for i
    do
      sed -n '/^Index:/q;/^---/q;/^diff /q;p' "$i"
    done
  fi
}

mark_in_progress ()
{
  if test -n "$1"; then
    echo "$1" > "$GILTROOT/.in-progress"
  else
    rm -f "$GILTROOT/.in-progress"
  fi
}

test_in_progress ()
{
  local op
  test -f "$GILTROOT/.in-progress" || return 1
  op=`cat "$GILTROOT/.in-progress"`
  test $op = "$1" || error $op in progress, continue or abort
  return 0
}

gilt_modified_files ()
{
  local absfile regex escape_regex pipe
  escape_regex='s,[][\\/.*^$],\\&,g'
  pipe=
  (cd "$GILTROOT/$GILTHEAD/tree" && find . -type f) |
  if test $# = 0; then
    sed 's,^\./,,'
  else
    regex=
    for i
    do
      make_svn_absolute_path absfile $i || error file not in the svn repository
      if test -z "$absfile"; then
        regex=^
        break
      fi
      if test -d "$SVNTOP/$absfile"; then  
        absfile=`echo "$absfile" | sed "$escape_regex" `
        regex="$regex$pipe^$absfile\\/"
      else
        absfile=`echo "$absfile" | sed "$escape_regex" `
        regex="$regex$pipe^$absfile\$"
      fi
      pipe='\|'
    done
    sed -ne 's,^\./,,' -e "/$regex/p"
  fi
}

do_commit ()
{
  local commit_msg_cmd patchfile basepatch newpatch
  set +e
  basepatch=$1
  if test "${2-'--'}" != --; then
    commit_msg_cmd=$2
    shift 3
  else
    commit_msg_cmd='if test -f "$patchfile"; then extract_commit_msg "$patchfile"; else echo; fi'
    shift 2
  fi
  newpatch=$(($basepatch + 1))
  patchfile="$GILTROOT/$GILTHEAD/patches/$newpatch"
  gilt_has_changes "$@" && error cannot commit empty changeset
  if (set -e
    { eval "$commit_msg_cmd"; echo; do_status "$@" | sed 's/^/# /'; } > "$patchfile.log"
    ${EDITOR-vi} "$patchfile.log"
    grep -v '^#' "$patchfile.log" | squeeze_blanks > "$patchfile.tmp"
    test -s "$patchfile.tmp" || error empty commit message, aborting
    egrep '^(---|+++|Index:)' "$patchfile.tmp" > /dev/null || error invalid commit message, aborting
    # undo last patch if amending
    if test -f "$patchfile"; then
      (test "$qvv" = -v || exec > /dev/null
      cd "$GILTROOT/$GILTHEAD/tree"
      doit $PATCH -p0 -R < "$patchfile")
    fi
    if cmd_diff "$@" > "$patchfile.patch"; then
      test "$qvv" = -v || exec > /dev/null
      cd "$GILTROOT/$GILTHEAD/tree"
      doit $PATCH -p0 < "$patchfile"
      error amended changeset would be empty
    else
      test "$qv" = -v || exec > /dev/null
      cd "$GILTROOT/$GILTHEAD/tree"
      doit $PATCH -p0 < "$patchfile.patch"
    fi
    doit false || { echo | cat "$patchfile.tmp" - "$patchfile.patch" > "$patchfile"; }); then
    NUMPATCHES=$newpatch
    doit save
    rm -f "$patchfile.log" "$patchfile.patch" "$patchfile.tmp"
    return 0
  else
    rm -f "$patchfile" "$patchfile.log" "$patchfile.patch" "$patchfile.tmp"
    return 1
  fi
}

do_add ()
{
  local dir file
  test -f "$GILTROOT/$GILTHEAD/tree/$1" && return 0
  test -d "$SVNTOP/$1" && return 0
  oldwd=$PWD
  cd "$SVNTOP"
  doit reconstruct tree "$1"
  notquiet echo "A	$1"
  cd "$oldwd"
}

do_rm ()
{
  if test "$1" = -f; then
    test -f "$GILTROOT/$GILTHEAD/tree/$2" || return 0
    shift
  fi
  test -f "$GILTROOT/$GILTHEAD/tree/$1" || error untracked file
  cmp "$SVNTOP/$1" "$GILTROOT/$GILTHEAD/tree/$1" > /dev/null || \
    error file "$1" has changes
  if test "$NUMPATCHES" -gt 0; then
    if grep -xF "Index: $1" "$GILTROOT/$GILTHEAD"/patches/* > /dev/null; then
      error patches have changes for "$1"
    fi
  fi
  doit rm -f "$GILTROOT/$GILTHEAD/tree/$1"
  notquiet echo "R	$1"
}

clear_stack ()
{
  NUMPATCHES=0
  FIRSTPATCH=
  BASEREV=`svn info $SVNROOT/$BRANCH | sed -n 's/Revision: //'`
  doit rm -rf "$GILTROOT/GILTHEAD"/patches/*
  doit save
}

update_head ()
{
  doit eval echo \""$1"\" \> \"\$GILTROOT/HEAD\"
}

start_rebase ()
{
  rm -rf "$GILTROOT/rebase-$GILTHEAD"
  mkdir_p "$GILTROOT/rebase-$GILTHEAD/patches"
  cp ${qvv} -R "$GILTROOT/$GILTHEAD/tree" "$GILTROOT/rebase-$GILTHEAD/tree"
  cmd_reset --force
  GILTHEAD=rebase-$GILTHEAD
  gilt_modified_files | while read file; do
    reconstruct next "$file"
  done
  if test "$#" -gt 0; then
    BRANCH=${1-SVNBRANCH}
    svn switch ${qv} $SVNROOT/$BRANCH
  else
    svn update ${qv}
  fi
  gilt_modified_files | while read file; do
    reconstruct tree "$file"
  done
  BASEREV=`svn_info Revision`
  NUMPATCHES=0
  save
  update_head "$GILTHEAD"
  mark_in_progress rebase
}

# Command implementations
# -----------------------

cmd_abort ()
{
  test -f "$GILTROOT/.in-progress" || return 0
  doit false && error cannot perform abort dry run
  eval abort_`cat "$GILTROOT/.in-progress"`
}

cmd_add ()
{
  local file
  get_gilt_info --need-branch
  if test "$1" = -a ; then
    cd "$SVNTOP"
    svn status | sed -n 's/^[AM]      //p' | while read absfile; do
      do_add $absfile
    done
  else
    for file
    do
      make_svn_absolute_path absfile $file || error file not in the svn repository
      do_add $absfile
    done
  fi
}

cmd_branch ()
{
  if test "$#" = 0; then
    get_gilt_info
    cd $GILTROOT
    ls */INFO | sed 's,/INFO$,,'
    echo current branch: ${GILTHEAD-'<none>'}
    return 0
  fi

  case "$1" in
    -d|-D)
      get_gilt_info
      curbranch="$GILTHEAD"
      test $# -ne 2 && error usage: gilt branch -d BRANCH
      get_gilt_info "$2"
      if test "$1" = -d && test "$NUMPATCHES" -gt 0; then
	error unpushed commits, cannot delete branch
      fi
      test "$GILTHEAD" = "$curbranch" && doit cmd_reset --soft --force
      doit rm -rf "$GILTROOT/$GILTHEAD"
      return 0
      ;;
    -*)
      error unknown branch option "\`$1'"
      ;;
    *)
      get_gilt_info --init
      case "$1" in
        -* | */*) error invalid character name in branch ;;
        *) test -d "$1" && error branch "\`$1'" already exists ;;
      esac
      set -e
      NUMPATCHES=0
      BRANCH=${2-$SVNBRANCH}
      if test "$BRANCH" != "$SVNBRANCH"; then
        check_no_changes please commit or discard changes before switching branch
        doit cmd_reset --soft --force
        doit svn_revert
        doit svn switch $qv $SVNROOT/$BRANCH
      fi
      BASEREV=`svn_info Revision`
      doit mkdir_p "$GILTROOT/$1/patches"
      doit mkdir_p "$GILTROOT/$1/tree"
      doit save "$1"
      set +e
      ;;
  esac
}

cmd_checkout ()
{
  if test $# = 0; then
    error expected branch name
  fi
  if test "$1" = -b; then
    if test $# -gt 3; then
      error usage: gilt checkout -b BRANCH SVN-BRANCH
    fi
    shift
    get_gilt_info
    OLDGILTHEAD=$GILTHEAD
    check_no_changes please commit or discard changes before branching
    doit cmd_branch "$@"
    get_gilt_info "$1"
    echo the changes in branch "\`$OLDGILTHEAD'" are still in the tre
    (cd "$GILTROOT/$OLDGILTHEAD/tree" && find . -type f) | while read file; do
      do_add "$file"
    done
  else
    if test $# -gt 1; then
      error usage: gilt checkout BRANCH
    fi

    get_gilt_info
    check_no_changes please commit or discard changes before switching branch
    test_gilt_branch "$1"
    cd $SVNTOP
    (set -e;
      if test -n "$GILTHEAD"; then
	doit svn_revert
	OLDGILTHEAD=$GILTHEAD
      fi
      get_gilt_info "$1"
      ok=:
      if check_no_overlapping_changes; then
	# Make sure to work disconnected if possible
	currev=`svn_info Revision`
	if test "$BRANCH:$BASEREV" != "$SVNBRANCH:$currev"; then
	  doit svn switch $qv -r$BASEREV $SVNROOT/$BRANCH
	fi
      else
	error_msg changes overlap branch being checked out, cannot proceed
	if test -z "$OLDGILTHEAD"; then
	  exit 1
	fi
	# Doh, we have to restore the status quo.
	get_gilt_info "$OLDGILTHEAD"
	ok=false
	qv=${qvv}
	cond_reset notquiet
      fi

      gilt_modified_files | while read file; do
        notquiet cmp "$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file" > /dev/null || echo "M	$file"
        doit cp ${qvv} "$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file"
      done
      $ok || exit 77)
    case $? in
      0) ;;
      77) return 1 ;;
      *)
	doit cmd_reset --force
	error errors occurred, no gilt branch is currently checked out ;;
    esac
  fi

  update_head "$1"
}

cmd_commit ()
{
  local add_all add_files amend

  get_gilt_info --need-branch

  # TODO: -m and -F options
  add_all=false
  add_files=false
  amend=false
  while test $# -gt 0; do
    case "$1" in
      -a)
        add_all=:
	shift
	;;
      --amend)
	amend=:
	shift
	;;
      -*)
	error invalid option "$1"
	;;
      *)
        add_files=:
	break
	;;
    esac
  done
  if $add_all && $add_files; then
    error cannot pass -a and files together
  elif $add_all; then
    doit cmd_add $qv -a
  elif $add_files; then
    doit cmd_add $qv "$@"
  fi
  if $amend; then
    test $NUMPATCHES -gt 0 || error cannot amend, no patch added to branch yet
    test $# -gt 0 || error --amend with paths not implemented yet
    do_commit $(($NUMPATCHES - 1)) -- "$@"
  else
    do_commit $NUMPATCHES -- "$@"
  fi
}

cmd_dcommit ()
{
  get_gilt_info --need-branch
  check_no_changes please commit or discard changes before dcommit
  i=${FIRSTPATCH:-1}
  cmd_reset
  cd "$SVNTOP"
  mark_in_progress dcommit
  set -e
  while test $i -le $NUMPATCHES; do
    echo Committing patch $i/$NUMPATCHES...
    patchfile=$GILTROOT/$GILTHEAD/patches/$i
    $PATCH -p0 --dry-run < "$patchfile" || \
      { mark_in_progress; echo conflicts, starting rebase; exec cmd_rebase; }
    i=$(($i + 1))
    BASEREV=`svn_info Revision`
    FIRSTPATCH=$i
    doit save
    doit $PATCH -p0 < "$patchfile"
    { doit svn commit "`extract_commit_msg "$patchfile"`"; } || \
      { mark_in_progress; echo concurrent commit, trying to rebase...; cmd_rebase; }
  done
  gilt_modified_files | while read line; do
    doit reconstruct tree "$file"
  done
  clear_stack
  mark_in_progress
}

abort_dcommit ()
{
  echo you should not have arrived here unless you halted the
  echo commit.  the only way out is to perform a rebase.
  echo type Ctrl-C to abort, or return to continue.
  read
  start_rebase
  cmd_rebase
}

cmd_diff ()
{
  local file
  get_gilt_info --need-branch
  if test $# = 0; then
    cd $SVNTOP
    SVNSUBDIR=
    set .
  fi
  if test "$qv" != -q; then
    gilt_modified_files "$@" | while read file; do
      cmp "$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file" > /dev/null 2>&1 && continue
      echo "Index: $file"
      echo '==================================================================='
      $DIFF $DIFFOPTS -L "$file	(branch $GILTHEAD)" \
	 -L "$file	(working copy)" \
	"$GILTROOT/$GILTHEAD/tree/$file" "$SVNTOP/$file"
    done
  fi
  gilt_has_changes "$@"
  return $?
}


cmd_import ()
{
  local plevel patchfile branchname
  get_gilt_info
  # TODO: add common handling of -m and -F to commit and import
  # TODO: add -R
  case "$1" in
    -p*) plevel=$1 ; shift ;;
    *) plevel=-p0 ;;
  esac
  test $# = 1 || error usage: gilt import '[-pN]' FILE
  patchfile="$1"
  $PATCH -f --dry-run "$plevel" < "$patchfile"
  case $? in
    1) error patch does not apply cleanly, aborting ;;
    2) return 1 ;;
  esac
  set -e
  if test -z "$GILTHEAD"; then
    branchname=`basename "$branchname"`
    branchname=${1%.*}
    notquiet echo not on a gilt branch, creating branch "$branchname"
    cmd_checkout -b "$branchname"
  fi
  doit $PATCH -f "$plevel" < "$patchfile" > /dev/null
  doit cmd_add $qv -a
  doit do_commit $NUMPATCHES --
}

cmd_init ()
{
  get_gilt_info --init
  test $# -gt 0 && doit checkout -b "$1"
}

cmd_log ()
{
  case "$1" in
    -r|--reverse) reverse=: ; shift; ;;
    *) reverse=false ;;
  esac

  if test -z "$1"; then
    get_gilt_info --need-branch
  else
    get_gilt_info "$1"
  fi

  if $reverse; then
    i=1
    while test $i -le $NUMPATCHES; do
      extract_commit_msg "$GILTROOT/$GILTHEAD/patches/$i"
      i=$(($i + 1))
    done
  else
    i=$NUMPATCHES
    while test $i -gt 0; do
      extract_commit_msg "$GILTROOT/$GILTHEAD/patches/$i"
      i=$(($i - 1))
    done
  fi
}

cmd_push ()
{
  get_gilt_info --need-branch
  check_no_changes please commit or discard changes before pushing
  set -e
  { cmd_log
  echo
  echo '--This line, and those below, will be ignored--'
  svn status | grep -v '^?'; } > "$GILTROOT/$GILTHEAD/log"
  ${EDITOR-vi} "$GILTROOT/$GILTHEAD/log"
  doit svn commit -F"$GILTROOT/$GILTHEAD/log"
  doit cmd_reset --soft
  doit clear_stack
  rm "$GILTROOT/$GILTHEAD/log"
}

cmd_rebase ()
{
  local i conflict_solved
  doit false && error cannot perform rebase dry run
  get_gilt_info --need-branch
  cd $SVNTOP
  if test_in_progress rebase; then
    test "$#" = 0 || error cannot switch, rebase in progress
    conflict_solved=:
  else
    check_no_changes please commit or discard changes before rebasing
    FIRSTPATCH=1
    start_rebase "$@"
    conflict_solved=false
  fi
  i=${FIRSTPATCH:-1}
  while :; do
    patchfile=$GILTROOT/${GILTHEAD#rebase-}/patches/$i
    test -f "$patchfile" || break
    echo Committing patch $i...
    $conflict_solved || {
      rm ${qvv} -rf "$GILTROOT/$GILTHEAD/base" 
      mv ${qvv} "$GILTROOT/$GILTHEAD/next" "$GILTROOT/$GILTHEAD/base" 
      cp ${qvv} -R "$GILTROOT/$GILTHEAD/base" "$GILTROOT/$GILTHEAD/next" 
      (cd "$GILTROOT/$GILTHEAD/next" && $PATCH -p0 < "$patchfile" > /dev/null)
      rm ${qvv} -rf "$GILTROOT/$GILTHEAD/tree-next"
      cp ${qvv} -R "$GILTROOT/$GILTHEAD/tree" "$GILTROOT/$GILTHEAD/tree-next" 
      (cd "$GILTROOT/$GILTHEAD/tree-next" && $PATCH -p0 < "$patchfile" > /dev/null) || {
        # Got conflicts
        gilt_modified_files | while read file; do
	  src=$SVNTOP/$file
	  older=$GILTROOT/$GILTHEAD/base/$file
	  next=$GILTROOT/$GILTHEAD/next/$file
          rm -f "$src~"
          if $DIFF -u "$older" "$next" | $PATCH "$src" -o "$src.new" > /dev/null; then
            echo "M	$file"
	  else
	    # Is there a way to mark it as conflicted in subversion?!?
            #cp "$next" "$src.mine"
	    echo "C	$file"
            diff3 -m -E "--diff-program=$DIFF" \
	      -L svn -L "patch $((i - 1))" -L "patch $i" \
	       "$src" "$older" "$next" > "$src.new"
          fi
          mv "$src.new" "$src"
        done
        return 1
      }

      gilt_modified_files | while read file; do
        cp ${qvv} "$GILTROOT/$GILTHEAD/tree-next/$file" "$SVNTOP/$file" && echo "M	$file"
      done
    }

    gilt_has_changes || {
      extract_commit_msg "$patchfile" > "$GILTROOT/log"
      do_commit $NUMPATCHES 'cat "$GILTROOT/log"' --
      rm -f "$GILTROOT/log"
    }

    # Move next to base for subsequent diff3 operations
    i=$(($i + 1))
    FIRSTPATCH=$i
    save
    conflict_solved=false
  done
  mark_in_progress
  GILTHEAD=${GILTHEAD#rebase-}
  mv "$GILTROOT/$GILTHEAD" "$GILTROOT/save-$GILTHEAD"
  mv "$GILTROOT/rebase-$GILTHEAD" "$GILTROOT/$GILTHEAD"
  rm -rf "$GILTROOT/save-$GILTHEAD"
  rm -rf "$GILTROOT/$GILTHEAD/base"
  rm -rf "$GILTROOT/$GILTHEAD/next"
  rm -rf "$GILTROOT/$GILTHEAD/tree-next"
  FIRSTPATCH=
  save "$GILTHEAD"
  update_head "$GILTHEAD"
}

abort_rebase ()
{
  get_gilt_info
  cmd_reset --force
  case "$GILTHEAD" in
    rebase-*) rm -rf "$GILTROOT/$GILTHEAD" ;;
    *) ;;
  esac
  mark_in_progress
}

cmd_reset ()
{
  local force soft
  force=false
  soft=false
  for i
  do
    case $i in
      --force) force=: ;;
      --soft) soft=: ;;
      *) error invalid option ;;
    esac
  done
  cd "$SVNTOP"
  $force || {
    get_gilt_info
    check_no_changes cannot reset
  }
  $soft || {
    get_gilt_info
    doit svn_revert
  }
  doit rm -f "$GILTROOT"/HEAD
}

cmd_rm ()
{
  local file f
  get_gilt_info --need-branch
  if test $1 = -f; then
    f=-f; shift
  fi
  for file
  do
    make_svn_absolute_path absfile $file || error file not in the svn repository
    do_rm $f $absfile
  done
}

cmd_show ()
{
  local all
  if test "$1" = -a; then
    all=:
    shift
  else
    all=false
  fi
  case "$1" in
    *[a-z]*) get_gilt_info "$1"; shift ;;
    *) get_gilt_info --need-branch ;;
  esac
  if $all; then
    i=1
    while test $i -le $NUMPATCHES; do
      echo patch "$i/$NUMPATCHES":
      cat "$GILTROOT/$GILTHEAD/patches/$i"
      i=$(($i + 1))
      echo
    done
  else
    if test $NUMPATCHES = 0; then
      echo branch is empty
    else
      patch=${1-$NUMPATCHES}
      test -f "$GILTROOT/$GILTHEAD/patches/$patch" || error invalid patch "\`$patch'"
      cat "$GILTROOT/$GILTHEAD/patches/$patch"
    fi
  fi
}

cmd_status ()
{
  local file
  get_gilt_info --need-branch
  if test $# = 0; then
    cd $SVNTOP
    SVNSUBDIR=
    set .
  fi
  do_status "$@"
  gilt_has_changes "$@"
  return $?
}

# Main driver
# -----------

# More sanitization (NLS nuisances).
for i in LANG LANGUAGE LC_ALL LC_COLLATE LC_CTYPE 
do
  eval $i=C; export $i
done

progname=$0
DIFF=${DIFF-diff}
PATCH=${PATCH-patch}
DIFFOPTS=${DIFFOPTS--p -u}

# Parse the -q, -v, -vv, --dry-run options
qv=
qvv=
dry_run=
cond_set notquiet
cond_reset quiet
cond_reset verbose
cond_reset debug
cond_set doit

first=:
for i
do
  # Clear options after for loop starts
  if $first; then
    set fnord
    first=false
  fi
  case "$i" in
    -x)
      set -x ;;	
    --dry-run)
      dry_run=--dry-run
      cond_reset doit ;;
    -q | --quiet)
      qv=-q
      cond_set quiet
      cond_reset notquiet
      cond_reset verbose
      cond_reset debug ;;
    -v | --verbose)
      qv=-v
      cond_reset quiet
      verbose cond_set debug
      cond_set notquiet
      cond_set verbose ;;
    -vv)
      qv=-v
      qvv=-v
      cond_reset quiet
      cond_set debug
      cond_set notquiet
      cond_set verbose ;;
    *)
      set "$@" "$i"
      ;;
  esac
done
shift

unset first
unset i

cmdname=${1-help}
shift
case $cmdname in
  --help|-h|help) usage ;;

  abort | add | branch | checkout | commit | dcommit | \
  diff | import | init | log | push | rebase | \
  reset | rm | show | status) ;;

  -*) usage_error unknown option "\`$cmdname'" ;;
  *) usage_error unknown command "\`$cmdname'" ;;
esac

get_svn_info
case $cmdname in
  abort | diff | log | show | status ) ;;
  *) test_in_progress "$cmdname" 
esac
eval cmd_$cmdname \"\$@\"
